# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gateway-server-deployment
serviceName: gateway-server
appLabel: gateway-server
appName: gateway-server

replicaCount: 1

image:
  repository: activerx-pharmacy/gateway-server
  tag: R04

containerPort: 8020

service:
  type: LoadBalancer
  port: 8020
  targetPort: 8020

appname_enabled: true
profile_enabled: true
eureka_enabled: false
