services:

  eureka-server:
    image: "activerx-pharmacy/eureka-server:R04"
    container_name: eureka-server-ms
    ports:
      - "8021:8021"
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"
    extends:
      file: common-config.yml
      service: level-1-service
    healthcheck:
      test: "curl --fail --silent localhost:8021/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s


  inventory-service:
    image: "activerx-pharmacy/inventory-service:R04"
    container_name: inventory-service-ms
    environment:
      SPRING_APPLICATION_NAME: "inventory-service"
    extends:
      file: common-config.yml
      service: level-2-application-base
    healthcheck:
      test: "curl --fail --silent localhost:8030/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s


  store-service:
    image: "activerx-pharmacy/store-service:R04"
    container_name: store-service-ms
    environment:
      SPRING_APPLICATION_NAME: "store-service"
    extends:
      file: common-config.yml
      service: level-2-application-base
    healthcheck:
      test: "curl --fail --silent localhost:8031/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  gateway-server:
    image: "activerx-pharmacy/gateway-server:R04"
    container_name: gateway-server-ms
    ports:
      - "8020:8020"
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
    extends:
      file: common-config.yml
      service: level-3-gateway-base
    healthcheck:
      test: "curl --fail --silent localhost:8020/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  activerx-pharmacy-network:
    driver: "bridge"