#
#
#   E U R E K A   S E R V E R  (8021)
#
#

server:
  port: 8021

info:
  app:
    name: "eureka-server"
    description: "Active Pharmacy - Eureka Server"
    version: "1.0.0"

spring:
  application:
    name: "eureka-server"
  profiles:
    active: "default"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
#  metrics:
#    tags:
#      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
    com:
      activerx-pharmacy:
        eureka-server: DEBUG
#  pattern:
#    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"