#
#
#   I N V E N T O R Y   S E R V I C E
#
#

server:
  port: 8030

info:
  app:
    name: "inventory-service"
    description: "Inventory Service v1"
    version: "1.0.0"

spring:
  application:
    name: inventory-service
  profiles:
    active: "default"
  datasource:
    url: "jdbc:mysql://localhost:3306/active_pharmacy_v2"
    username: root
    password: Test12345
  jpa:
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#    hibernate:
#      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8021/eureka/