#
#
#   G A T E W A Y - S E R V E R  (8020)
#
#

server:
  port: 8020

info:
  app:
    name: "gateway-server"
    description: "Active Pharmacy - Gateway Server"
    version: "1.0.0"

spring:
  application:
    name: gateway-server
  profiles:
    active: "default"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s
  r2dbc:
    url: "r2dbc:mysql://localhost:3306/active_pharmacy_v2"
    username: root
    password: Test12345
# R02 : Resilience.RateLimiter
#  data:
#    redis:
#      connect-timeout: 2s
#      host: localhost
#      port: 6379
#      timeout: 1s
# R03 : Security Keycloak
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: "http://localhost:8016/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
# R01 : Observability
#  metrics:
#    tags:
#      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8021/eureka/

logging:
  level:
    com:
      activerx-pharmacy:
        gateway-server: DEBUG
# R01 : Observability
#  pattern:
#    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

jwt:
  token-expiration-seconds: 3600
  secret-key: "Vr3snA4K8Mfihp4twIHdxc0Vym+v7e7jlBgyZRBjZMM1yjKOvs24++a3AxBLrrCQ9KmXRfhxcl2KlNGmblD+eA=="

