#
#
#   S T O R E   S E R V I C E  (8031)
#
#

server:
  port: 8031

info:
  app:
    name: "store-service"
    description: "Store Service v1"
    version: "1.0.0"

spring:
  application:
    name: store-service
  profiles:
    active: "default"
  datasource:
    url: "jdbc:mysql://localhost:3306/active_pharmacy_v2"
    username: root
    password: Test12345
  jpa:
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#    hibernate:
#      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8021/eureka/

logging:
  level:
    com:
      activerx-pharmacy:
        store-service: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"